version: '3.6'

networks:
    proxy:
        external: true
        name: proxy
    internal:
        name: internal

services:
    db_rsis_edu:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE}
        networks:
            - internal
        ports:
            - "15433:5432"

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./app:/app
            - ./.docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
        networks:
            - internal
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.rsis_edu_backend.rule=Host(`localhost`)"
            - "traefik.http.services.rsis_edu_backend.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy"

    php:
        build: .docker/php
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app
            - ./.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini:ro
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./.docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisor.conf:ro
        networks:
            - internal
        ports:
            - "9501:9501"
